// export const metadata = {
//     title: "Bm Box",
//     description: "Generated by create next app",
// };
export default function About() {
    return (
        <div>
            <h1>About Page</h1>
            <p>Welcome to my Next.js app!</p>
        </div>
    );
}
