import Image from "next/image";
import styles from "./styles/page.module.css";
import Head from "next/head";
import Link from "next/link";
import ScrollingContainer from "./components/ScrollingContainer";

export const metadata = {
    title: "Boom Box",
    description: "Generated by create next app",
};

const data = ["Image 1", "Image 2", "Image 3", "Image 4", "Image 5", "Image 6", "Image 7", "Image 8"];

export default function Home() {
    return (
        <>
            <section className={styles.main}>
                <div className="center">
                    <h1>Share Photos, Get the Perfect Song</h1>
                    <p>Upload a photo, and let BoomBox automatically match it with a song that fits the vibe.</p>
                    <Link href="/" className="topgap cta right">
                        Get Started
                    </Link>
                </div>

                <div className={styles.disc}>
                    <img src="/disc2.png"></img>
                </div>
            </section>
            <section className={styles.section2}>
                <div className="topcenter">
                    <h1>Latest Posts</h1>
                    <p>Check out the most recent photos shared with their perfect song pairings. See what's trending!</p>
                    <ScrollingContainer data={data} />
                </div>
            </section>
            <section className={styles.section3}>
                <div className="topcenter">
                    <h1>How it Works</h1>
                    <div>
                        <ol>
                            <li>
                                Upload Your Photo <p>Choose a photo from your gallery or take a new one.</p>
                            </li>
                            <li>
                                Instant Song Matching <p>Our app automatically matches a song to your photo, creating the perfect vibe.</p>
                            </li>
                            <li>
                                Share and Enjoy <p>Share your photo and song combo with friends, or save it for later!</p>
                            </li>
                        </ol>
                    </div>
                    <Link href="/" className="topgap cta right">
                        Get Started
                    </Link>
                </div>
            </section>
        </>
    );
}
