import Image from "next/image";
import styles from "./styles/page.module.css";
import Head from "next/head";

export const metadata = {
    title: "Boom Box",
    description: "Generated by create next app",
};

export default function Home() {
    return <></>;
}
